# Generated by Django 3.0.2 on 2020-01-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='members_list',
            new_name='members_limit',
        ),
    ]
